### ISSUE TITLE
Unable to unmarshal file.

### ISSUE THREAD

**Issue by AMetnik** [eclipse-ee4j/jaxb-ri#1598]
```
C:\Users\anmet\Downloads>C:\Users\anmet\Downloads\jaxb-ri-2.3.1\jaxb-ri\bin\xjc.bat SalesDataInterface.xsd
Java major version: 8
parsing a schema...
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/rngdatatype/ValidationContext
        at com.sun.xml.xsom.impl.parser.ParserContext.newNGCCRuntime(ParserContext.java:154)
        at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
        at com.sun.xml.xsom.impl.parser.ParserContext.<init>(ParserContext.java:104)
        at com.sun.xml.xsom.parser.XSOMParser.<init>(XSOMParser.java:113)
        at com.sun.tools.xjc.ModelLoader.createXSOMParser(ModelLoader.java:408)
        at com.sun.tools.xjc.ModelLoader.createXSOMSpeculative(ModelLoader.java:481)
        at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:340)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:151)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:106)
        at com.sun.tools.xjc.Driver.run(Driver.java:354)
        at com.sun.tools.xjc.Driver.run(Driver.java:221)
        at com.sun.tools.xjc.Driver._main(Driver.java:144)
        at com.sun.tools.xjc.Driver.access$000(Driver.java:82)
        at com.sun.tools.xjc.Driver$1.run(Driver.java:103)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.rngdatatype.ValidationContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 14 more

C:\Users\anmet\Downloads>java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

C:\Users\anmet\Downloads>java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```

**Comment by lukasj** [comment]
can you try with 2.3.4?

**Comment by AMetnik** [comment]
I'd love to, can you tell me where I can find a download for them, i've been looking for the new versions, also see on [https://projects.eclipse.org/projects/ee4j.jaxb-impl/governance](link) that there's a 3.0.1 version, but no where can I see a download?

**Comment by lukasj** [comment]
all versions are available via maven: https://search.maven.org/artifact/com.sun.xml.bind/jaxb-ri/2.3.5/pom direct link for 2.3.5 is https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-ri/2.3.5/jaxb-ri-2.3.5.zip

**Comment by AMetnik** [comment]
Thanks for that.

I sadly still get an error, but it's different this time:

```
C:\Users\anmet\Downloads>C:\Users\anmet\Downloads\jaxb-ri-2.3.5\jaxb-ri\bin\xjc.bat SalesDataInterface.xsd
Java major version: 8
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/istack/tools/MaskingClassLoader
        at com.sun.tools.xjc.XJCFacade.main(XJCFacade.java:74)
Caused by: java.lang.ClassNotFoundException: com.sun.istack.tools.MaskingClassLoader
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

```

**Comment by AMetnik** [comment]
I forgot to shut down and start up the cmd after changing environment variables, seems to work on 2.3.5. Thanks a bunch!

**Comment by AMetnik** [comment]
3.0.2 also confirmed working. Thanks for the aid.
