### ISSUE TITLE
NPE when running Jakarta versions on Java 8

### ISSUE THREAD

**Issue by beikov** [eclipse-ee4j/jaxb-ri#1538]
Hi,

I just tried to run an annotation processor which uses the Jakarta versions to parse XML on Java 8 and I see the following error:

```
Caused by: java.lang.NullPointerException
	at jakarta.xml.bind.ContextFinder.handleClassCastException(ContextFinder.java:114)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:254)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:375)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
```

I suppose that the JAXB implementation in Java 8 is used which does not implement the Jakarta APIs. This in itself is problematic already. The stacktrace then suggests that during error reporting it fails to find the class file `jakarta/xml/bind/JAXBContext.class` through the class loader of the problematic implementation.

Not sure if this is a problem in the API artifact or the implementation, but either way, it seem that using Jakarta JAXB on Java 8 is currently not possible.

**Comment by lukasj** [comment]
any steps to reproduce?

**Comment by beikov** [comment]
Here is a reproducer for this [jakarta-jaxb-issue.zip](https://github.com/eclipse-ee4j/jaxb-ri/files/6375413/jakarta-jaxb-issue.zip)

**Comment by lukasj** [comment]
works fine with jaxb 3.0.1

**Comment by beikov** [comment]
Am I understanding this correctly that this was fixed by https://github.com/eclipse-ee4j/jaxb-ri/commit/9de1e0aabe19e17180fe91eba3f13217dbcc947a ? When do you plan to release 3.0.1? It's not yet on Maven Central: https://search.maven.org/artifact/jakarta.xml.bind/jakarta.xml.bind-api

**Comment by lukasj** [comment]
probably but there were more changes - in api as well as in the implementation. I hope 3.0.1 will make it to central later today (or during this week), it's already in staging repo, so it's just about hitting the right button...
